' Contains edge cases once some or all inventory items are missing
' during the date of Installation


@startuml
    title Edge Cases
    start
    
    :STF starts to select items from HUB;
    note
        Selection of items should happen
        within the required selection period
    end note

    if (Are some or **ALL** items missing from HUB?) then (Yes)
        fork
            :HUB Adds the required inventory to the system;
            #SkyBlue:HUB informs STF that the
            items in question are available;
            note #YellowGreen
                Does this appear as an
                icon in the dashboard,
                a change of color, 
                or something else?
            end note
        fork again
            :STF negotiates with Client to
            delay the install date and time
            until all items are available;

            if (Client Accepts delay?) then (Yes)
                :STF changes the Installation Date and Time
                based on the new agreed Date and Time;

                note right #PaleVioletRed
                    I want to avoid another situation
                    that someone else has reserved
                    the items before me,
                    thereby causing this delay.

                    Is it possible to reserve even
                    before the t - 7 day window?
                end note
            else (No)
                #SkyBlue:STF delivers the job with
                some items still missing.;

                :STF selects the furniture
                that can be delivered;

                #SkyBlue:Job continues as in normal case
                but it should show an indication
                that some items are **not** yet delivered;
            endif
        end fork

    else (No)
        :STF selects all the needed items;
    endif

@enduml