' Shows the transitions of Job from Ready for Delivery To Completed

@startuml
    title Mobile: Job state flow
    start

    #LightBlue:Job state is //Selection//;

    :HUB staff checks which Jobs
    are //Ready for Picking//;

    note right
        //Ready for Picking// is shown in the 
        mobile app but //Selection// is shown in
        both STF and HUB's views.
    end note
    
    :HUB staff checks the
    items needed for the job;

    :HUB staff selects items from shelves,
    scans them, and places them into box(es);

    note right
        The act of scanning assigns
        a specific SKU to the Job.
    end note

    #SpringGreen:HUB Staff finishes selecting items;

    :HUB staff will assign the Job 
    **and all items he/she has picked**
    to a specific truck bay;

    #LightBlue:Job state will change to //Ready for Delivery//;

    #SpringGreen:Truck arrives and waits at the specific truck bay;

    :HUB staff will scan the items
    and place them in the truck;
    
    #SpringGreen:Truck Driver reaches Job Site;
    
    :HUB Staff scans the items which
    will be offloaded to the Job Site;

    note right
        There is another HUB Staff
        other than the driver who accompanies him/her to the site.
    end note

    #LightBlue:Job state will change to //On Job Site//;

    #SpringGreen:Client's event is finished;
    :Truck driver arrives on the Job Site;
    :HUB staff scans the items and loads them into the truck;
    #LightBlue:Job state will change to //Pick-up//;


    if(Are some items missing?) then (Yes)
        :Truck driver marks the item as //Missing//;

        note left #PaleVioletRed
            Clarify if Products
            have //Missing// status?
        end note

    elseif(Do some items need repairing?) then (Yes)
        :Truck driver marks the item as //Needing repair//;

        note left #PaleVioletRed
            Don't we need this kind of state?
        end note
    else(All loaned items\nare in good condition)
    endif

    :Job state is updated to //Pick-Up//;
    :Truck driver arrived at the HUB;
    :HUB staff unloads all the items;
    :Job state changes to //Completed//;
    stop
@enduml