' Shows the transitions of Job from Ready for Delivery To Completed

@startuml
    title Mobile: Job state flow
    start

    #LightBlue:Job state is //Selection//;

    :HUB staff checks which Jobs
    are //Ready for Picking//;

    note right
        //Ready for Picking// is shown in the 
        mobile app but //Selection// is shown in
        both STF and HUB's views.
    end note
    
    :HUB staff selects items from shelves,
    scans them, and places them into box(es);

    note right
        The act of scanning assigns
        a specific SKU to the Job.
    end note

    #SpringGreen:HUB Staff finishes selecting items;

    :HUB staff will assign the Job 
    and all items he/she has picked for it
    to a specified truck bay;

    #LightBlue:Job state will change to //Ready for Delivery//;

    #SpringGreen:Truck arrives and waits at the specified truck bay;

    :HUB staff will scan the items
    and place them in the truck;

    #SpringGreen:Truck Driver drives to Job Site;
    
    :HUB Staff scans the items which
    will be offloaded to the Job Site;

    note right
        There is a HUB Staff
        who accompanies the driver.
    end note

    #LightBlue:Job state will change to //On Job Site//;

    #SpringGreen:Client's event is finished;
    :Truck driver arrives on the Job Site;
    :HUB staff scans the items and loads them into the truck;

    if(Are some items missing?) then (Yes)
        #PaleVioletRed:HUB Staff marks the item as //Missing//;
        else(No)
    endif

    #LightBlue:Job state will change to //Pick-up//;

    #SpringGreen:Truck driver returned to HUB;
    :HUB staff scans all the items as he/she unloads them;
    #LightBlue:Job state will change to //Returned//;

    note right
        There is no //Returned// Job state.
    end note

    if(Do some items need repairing?) then (Yes)
        #PaleVioletRed:HUB Staff marks the item as //Needing repair//;
    else(No)
    endif

    #LightBlue:Job state changes to //Completed//;
    stop
@enduml