' STF wants to create Consultations

@startuml
    title STF creates Consultations

    actor "STF" as STF

    STF  -> UI: Click //Start a Job// button
    UI -> UI: Show //Create a Job// page
    STF -> UI: Click //Book a Consult// button
    UI -> UI: Show //Book a Consult// page
    STF -> UI: Enter the following details\n\t1. Client Details\n\t2. Agent Details\n\t3. Consult Details

    STF -> UI: Click //Book// button

    UI -> Backend: Save all data
    Backend -> Database: Save all data

    note over STF, Database #LimeGreen
        1. It should be possible to reuse this data when a Consult is converted to a Quote
        2. Shouldn't booking the consult //<u>automatically place the Consult Details to the STF's calendar?</u>//
    end note
@enduml