' STF creates Quotes without first creating a consultation

@startuml

    actor "STF" as STF

    note over STF, UI #GreenYellow
        It should be possible to automatically
        get data from an existing Consultation
    end note

    group Job Page 
        STF  -> UI: Click //Start a Job// button
        UI -> UI: Show //Create a Job// page
    end group
    
    group Start a Quote 
        STF -> UI: Click //Start a Quote// button
        UI -> UI: Show //Start a Quote// page
        STF -> UI: Enter details about the Client

        note over STF, UI #White
            * Client Details
            * Additional Client Details
        end note

        STF -> UI: Click //Next// button
    end group

    group Agent / Referrer Details 
        UI -> UI: Show //Agent / Referrer Details// page
        STF -> UI: Enter details about the Agent / Referrer
        STF -> UI: Click //Next// button
    end group

    group Install & Access
        UI -> UI: Show //Install & Access// page
        STF -> UI: Enter the following details
        note over STF, UI #White
            * Access Via
            * Occupancy 
            * Install Date
            * Install Access Notes
        end note

        opt STF wants to add Lift information
            STF -> UI: Click //Add Lift Info// button 
            UI -> UI: Expand section for STF to add lift Info
            STF -> UI: Enter Lift details.
        end

        STF -> UI: Click //Next// button
    end group

    group Brief
        UI -> UI: Show //Brief// page
        STF -> UI: Select **one or multiple** items for the desired look and feel

        note over STF, UI #PaleVioletRed
            We need to know whether STF can
            select multiple items for //Look and Feel// values.
        end note
        
        STF -> UI: Writes notes regarding pages in Portfolio that
        note over STF, UI #White
            * Clients love
            * Clients Do **NOT** love
        end note

        STF -> UI: Click //Next// button
    end group

    group Styling Proposal
        STF -> UI: Select desired **Mood Board**

        note over STF, UI #PaleVioletRed
            What is Mood Board?
            How is it different from the
            //Look and Feel// Section in the //Brief// page?
        end note
    end group
    
    UI -> Database: Save all data

@enduml