@startuml
    title STF: High-level Business Flow until //Open Quote// State
    start
    :STF clicks //Start a Job// button;

    if (Prior Consultation exists?) then (Yes)
        :Go to //Your Quotes & Consultations Page//;
        :Select Row with //Consultation// as its state;
        :STF clicks //Book// button;
    else (No. So STF clicks //Start a Job//)
        if (Book a Consult?) then (Yes)
            :Enter Details about:
                1. Client
                2. Agent
                3. Consult Details;

            :STF clicks //Book// button;
        else (No. STF clicks //Start a Quote//)
            :STF enters the following:
                1. Client(s) Details
                2. Agent / Referrer details
                3. Install and Access details
                4. information about the desired look and feel
                5. Styling Proposal
                6. Additional Services;

            :STF sees a summary of his/her Quotation;
        endif
    endif
    :Quote now has a state of //Open Quote//;
    stop
@enduml