@startuml
    title STF creates Quotes with data from a Prior Consultation
    start
    
    if (STF goes to Consultations Dashboard?) then (Yes)
        :STF clicks the Chevron (>>) button;
        :UI displays Client Details;
        :STF clicks //Next//;
        :UI displays Agent Details;
    else (STF clicks\nStart a Job)
        :STF enters the client's name
        in the Search field;
        if (A record of the client's name exists?) then (Yes)
            :UI shows a small pop-up
            window that STF can select;
            :STF selects the desired Client details;
            :UI displays Client Details;
            :STF clicks //Next//;
            :UI displays Agent Details;
        else (No)
            #LimeGreen:STF enters the client's
            details and his/her Agent;
        endif
    endif

    #LimeGreen:See <u>//STF creates Quotes without first creating a consultation//</u> diagram;

    stop

@enduml