@startuml
    title STF creates Quotes with data from a Prior Consultation

    actor "STF" as STF
    
    STF -> UI: Go to //Your Quotes & Consultations Page//
    STF -> UI: Select Row with Status //Consultation//
    UI -> UI: Opens //Book a Consult// Page

    group Book a Consult Page
        STF -> UI: Click //Book// button
        UI -> Backend: Fetch data associated with the specific Consultation
        Backend -> Database: Fetch data associated with the specific Consultation
        Database -> Backend: Return data
        Backend -> UI: Display data 

        UI -> STF: Shows details from Previous Consultation
    end group

    alt STF clicks Book
        UI -> Backend: Update consultation to booking
        Backend -> Database: Update consultation to booking
        Database -> Backend: //Success//
        Backend -> UI: //Success//

        UI -> UI: //Done// page is displayed
        STF -> UI: Clicks //Push to Calendar//

        note over STF, UI #LawnGreen
            Isn't it better to automatically
            send the consultation details to STF's calendar 
            once he/she clicks //Book//?
        end note
    else STF clicks Cancel
        note over STF, UI
            UI displays //Your Quotes & Consultations// Page again
        end note
    end
@enduml