' Contains the High-level flow of Jobs
' Pre-requisite: Quote has been approved by Client

@startuml
    title STF: High-level Business Flow for Jobs
    start
    :STF clicks //Jobs// button;
    :STF clicks the job with //Selection// status;

    fork
        if (STF wants to\nadd a room?) then (Yes)
            #GreenYellow:STF adds a room;

            note left
                Does this mean that when STF adds a room
                which is **NOT** part of the original quote,
                that the furniture(s) and service(s) for
                the said room(s) are **FREE**?
            end note
        else(No)
            :STF sticks to the\nnumber of rooms\nin the Quote;
        endif
    fork again
        if (STF clicks //Client Quote?//) then (Yes)
            ://Your Styling Proposal// view is shown;
            :STF clicks the //Accept Proposal// button;

            note right #PaleVioletRed
                **!!THIS IS WRONG!!** 
                STF should not have this button.
                Only client does.

                Links to //Your Styling Proposal// have to be edited
                to avoid confusion
            end note
        else (No)
        endif
    fork again
        if (STF wants to cancel the Job?) then (Yes)
            :STF enters the Job number in the dialog box;
            :STF clicks the //Archive// button;

            note right
                Why is the dialog box asking if STF wants to
                //"archive"// the job when //Cancel Job//
                button is clicked?
            end note
            #SkyBlue:Job status becomes //Archived//;

            note right #GreenYellow
                There is no //Archived// status yet.
                How should archived Jobs and/or Quotes be displayed?
                Do they have a separate tab on the left of the main page?
            end note
        else (No)
        endif
    end fork
    
    #SkyBlue:View is in the //Job// page;

    repeat :STF chooses furniture(s) for the room;
        :STF chooses the number of items
            for the specific furniture(s);
        :STF clicks //Add to selection// button;
    repeat while (Are there other rooms?) is (yes)
    
    #GreenYellow:There is no option to Add Services
    once Quote has been accepted by client.
    I need to verify this.;
    
    stop
@enduml