' Diagram containing flow from Open Quote state to Job
' NOTE:
' This is pure speculation on my end since wireframes
' are not clear as to how this should work

@startuml
    title STF: High-level Business Flow from //Open Quote// to //Job// state
    start
    :STF clicks Quotes section;
    :STF selects a Job with an //Open Quote// state;
    
    if () then (Click the **Pencil** icon to the\nleft of //Open Quote// state)
    else (click //Open Quote// text)

    note
        Both of these branches lead
        to the //Summary Page//
    end note
    
    endif
        :UI shows the Summary page;
        :STF clicks //Next//;
        
        note left
            //Done// page is shown.
        end note
        :STF clicks //Copy Quote Link//;
        :STF sends an email to Client containing
        the //Quote Link//;

        note left #OrangeRed
            It is **NOT** possible to
            send an email from the website YET. 

            However, I need to clarify this expectation.
        end note

        if (Client approves quote?) then (Yes)
            #SkyBlue:Quote becomes a //Job//;
        else (No)
            #OrangeRed:Quote becomes //Rejected//;

            note right
                There is no //Rejected// state yet.
            end note
        endif
    stop
@enduml